#! /usr/bin/env python
# -*- coding: utf-8 -*
import collections
from .base import BaseDownloader


class LanguageDownloader(BaseDownloader):
    PROCESSED_TABLE_NAME = 'language'
    RAW_TABLE_NAME = 'B16001'
    RAW_FIELD_CROSSWALK = collections.OrderedDict({
        '001E': 'total',
        '002E': 'only_english',
        '004E': 'spanish_and_english',
        '005E': 'spanish_no_english',
        '007E': 'french_and_english',
        '008E': 'french_no_english',
        '010E': 'haitian_and_english',
        '011E': 'haitian_no_english',
        '013E': 'italian_and_english',
        '014E': 'italian_no_english',
        '016E': 'portuguese_and_english',
        '017E': 'portuguese_no_english',
        '019E': 'german_and_english',
        '020E': 'german_no_english',
        '022E': 'other_germanic_and_english',
        '023E': 'other_germanic_no_english',
        '025E': 'greek_and_english',
        '026E': 'greek_no_english',
        '028E': 'russian_and_english',
        '029E': 'russian_no_english',
        '031E': 'polish_and_english',
        '032E': 'polish_no_english',
        '034E': 'serbo_croatian_and_english',
        '035E': 'serbo_croatian_no_english',
        '037E': 'other_slavic_and_english',
        '038E': 'other_slavic_no_english',
        '040E': 'armenian_and_english',
        '041E': 'armenian_no_english',
        '043E': 'persian_and_english',
        '044E': 'persian_no_english',
        '046E': 'gujarati_and_english',
        '047E': 'gujarati_no_english',
        '049E': 'hindi_and_english',
        '050E': 'hindi_no_english',
        '052E': 'urdu_and_english',
        '053E': 'urdu_no_english',
        '055E': 'punjabi_and_english',
        '056E': 'punjabi_no_english',
        '058E': 'bengali_and_english',
        '059E': 'bengali_no_english',
        '061E': 'other_indic_and_english',
        '062E': 'other_indic_no_english',
        '064E': 'other_indoeuropean_and_english',
        '065E': 'other_indoeuropean_no_english',
        '067E': 'telugu_and_english',
        '068E': 'telugu_no_english',
        '070E': 'tamil_and_english',
        '071E': 'tamil_no_english',
        '073E': 'other_dravidian_and_english',
        '074E': 'other_dravidian_no_english',
        '076E': 'chinese_and_english',
        '077E': 'chinese_no_english',
        '079E': 'japanese_and_english',
        '080E': 'japanese_no_english',
        '082E': 'korean_and_english',
        '083E': 'korean_no_english',
        '085E': 'hmong_and_english',
        '086E': 'hmong_no_english',
        '088E': 'vietnamese_and_english',
        '089E': 'vietnamese_no_english',
        '091E': 'khmer_and_english',
        '092E': 'khmer_no_english',
        '094E': 'other_tai_kadai_and_english',
        '095E': 'other_tai_kadai_no_english',
        '097E': 'other_asia_and_english',
        '098E': 'other_asia_no_english',
        '100E': 'tagalog_and_english',
        '101E': 'tagalog_no_english',
        '103E': 'other_austronesian_and_english',
        '104E': 'other_austronesian_no_english',
        '106E': 'arabic_and_english',
        '107E': 'arabic_no_english',
        '109E': 'hebrew_and_english',
        '110E': 'hebrew_no_english',
        '112E': 'other_afroasiatic_and_english',
        '113E': 'other_afroasiatic_no_english',
        '115E': 'other_western_africa_and_english',
        '116E': 'other_western_africa_no_english',
        '118E': 'other_centeral_eastern_southern_africa_and_english',
        '119E': 'other_centeral_eastern_southern_africa_no_english',
        '121E': 'navajo_and_english',
        '122E': 'navajo_no_english',
        '124E': 'other_native_north_america_and_english',
        '125E': 'other_native_north_america_no_english',
        '127E': 'other_unspecified_and_english',
        '128E': 'other_unspecified_no_english'
    })

    def _process_raw_data(self, *args, **kwargs):
        """
        Combine language counts to get total english/non-english speakers
        """
        df = super()._process_raw_data(*args, **kwargs)

        languages = [
            'spanish',
            'french',
            'haitian',
            'italian',
            'portuguese',
            'german',
            'other_germanic',
            'greek',
            'russian',
            'polish',
            'serbo_croatian',
            'other_slavic',
            'armenian',
            'persian',
            'gujarati',
            'hindi',
            'urdu',
            'punjabi',
            'bengali',
            'other_indic',
            'other_indoeuropean',
            'telugu',
            'tamil',
            'other_dravidian',
            'chinese',
            'japanese',
            'korean',
            'hmong',
            'vietnamese',
            'khmer',
            'other_tai_kadai',
            'other_asia',
            'tagalog',
            'other_austronesian',
            'arabic',
            'hebrew',
            'other_afroasiatic',
            'other_western_africa',
            'other_centeral_eastern_southern_africa',
            'navajo',
            'other_native_north_america',
            'other_unspecified'
        ]
        
        df[f'total_english'] = df['only_english'] + df[[f'{l}_and_english' for l in languages]].sum(axis=1)
        df[f'total_no_english'] = df[[f'{l}_no_english' for l in languages]].sum(axis=1)

        return df
